---
- name:
  hosts: all
  become: yes
  tasks:
   
    - name: remove_soft
      yum: name = {{item}} state = absent   
      loop:
        - httpd
        - zabbix_agent
        - docker 
        - docker-ce
        - docker-client 
        - docker-client-latest 
        - docker-common 
        - docker-latest 
        - docker-latest-logrotate 
        - docker-logrotate 
        - docker-engine
